version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    links:
      - zookeeper
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $LOCALHOSTNAME
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    links:
      - zookeeper
    depends_on:
      - zookeeper
      - kafka1
    ports:
      - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $LOCALHOSTNAME
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    links:
      - zookeeper
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
    ports:
      - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $LOCALHOSTNAME
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_CREATE_TOPICS: "Topic1:10:3,Topic2:20:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
